import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {prepareAdditionalAircraft} from '../additional-aircraft.js';
import {prepareCorsair} from '../corsair.js';
import {prepareF16,prepareSeaplane} from '../aircraft-rigs.js';
import {prepareCaproni} from '../caproni.js';
import {prepareLab} from './index.js';
import {repairMaterials,visibleBounds,presetState} from '../rig-tools.js';
const assets={spitfire:'fg-spitfire-spitfirevb-371986bf',seafire:'fg-spitfire-seafireiiic-e1e7c198',f4u:'fg-f4u-8cea7feb',f16:'fg-f16-defa67fc',dauphin:'fg-dauphin-ea380a4c',ec130:'fg-ec130-9797aa83',bo105:'fg-bo105-5f1245bd',eflash:'fg-e-flash-c73b47ce',m33:'fg-macchi-m33-70f57d9d',s6b:'man-supermarine-s-6b-366f4f6d',mc72:'man-macchi-castoldi-mc72-6fa2f786',ca60:'man-caproni-ca60-e193e5f3'};
const refPrefix={spitfire:'09_',seafire:'05_',f4u:'05_',f16:'08_',dauphin:'05_',ec130:'04_',bo105:'02_',eflash:'06_',m33:'04_',s6b:'02_',mc72:'03_',ca60:'04_'};
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search),id=query.get('id')??'spitfire',asset=assets[id],page=Number(query.get('page')??0),candidateMode=query.has('candidates'),meta=await fetch('/meta/'+asset).then(r=>r.json());
$('title').textContent=`${meta.title} · ${candidateMode?'geometry candidates':'ChatGPT / Lab / reference'}`;
document.body.classList.toggle('candidates',candidateMode);
if(candidateMode&&id==='ca60'){
 const style=document.createElement('style');style.textContent='body.candidates #panels{grid-template-columns:repeat(3,minmax(0,1fr))}body.candidates .view{height:380px}body.candidates .notes{min-height:44px}';document.head.append(style);
}
$('candidateLink').href=`/?id=${id}&candidates=1&page=0`;$('prev').href=`/?id=${id}&candidates=1&page=${Math.max(0,page-1)}`;$('next').href=`/?id=${id}&candidates=1&page=${page+1}`;
if(!candidateMode){$('prev').hidden=true;$('next').hidden=true;}
const views=[],loader=new GLTFLoader();let parked=true,current=presetState(true),cameraView='side';
function original(root,animations){if(['spitfire','seafire','eflash','dauphin','ec130','bo105'].includes(id))return prepareAdditionalAircraft(root,id);if(id==='f4u')return prepareCorsair(root);if(id==='f16')return prepareF16(root);if(id==='ca60')return prepareCaproni(root);return prepareSeaplane(root,animations);}
function panel(label,notes=''){const p=document.createElement('section');p.className='panel';const l=document.createElement('div');l.className='label';l.textContent=label;const view=document.createElement('div');view.className='view';const n=document.createElement('div');n.className='notes';n.textContent=notes;p.append(l,view,n);$('panels').append(p);return view;}
async function model(url,label,kind){
 const div=panel(label,kind==='alternate'?'User cleared supplied alternates · provenance required':kind==='repaired-base'?'Existing Ca.60 repair excludes exploded parts and restores wing banks / rudders; existing paint shown.':kind==='raw'?'Exact download · untouched geometry':kind==='lab'?'Original-download rig and paint':'Existing version preserved');
 try{const gltf=await loader.loadAsync(url),root=gltf.scene;repairMaterials(root);
 if(candidateMode&&id==='ca60'&&kind==='alternate'&&url.includes('man-caproni-ca60-1dec6a9e')){
  const sea=root.getObjectByName('Sea'),water=[];sea?.traverse(o=>{if(o.isMesh)water.push(o);});
  if(water.length!==2||water.some(o=>Array.isArray(o.material)||!['water','waterSide'].includes(o.material.name)))throw Error('Sea display platform topology changed; inspect before excluding it.');
  sea.visible=false;sea.userData.reviewHiddenReason='Named Sea display platform; not part of the aircraft.';
  div.parentElement.querySelector('.notes').textContent='Aircraft geometry unchanged; named Sea water / waterSide display platform hidden for this comparison only.';
 }
 let hasGeometry=false;root.traverseVisible(o=>{if(o.isMesh&&o.geometry.attributes.position?.count)hasGeometry=true;});
 if(!hasGeometry){div.textContent='No aircraft geometry in this supplied GLB.';div.style.cssText='display:grid;place-items:center;padding:20px;box-sizing:border-box;text-align:center';div.parentElement.querySelector('.notes').textContent='The file contains only an empty node named radiator2479.obj; there are no meshes or vertices to borrow.';return;}
 let rig=kind==='lab'?await prepareLab(root,gltf.animations,{baseId:id,file:asset+'.glb'}):['chatgpt','repaired-base'].includes(kind)?original(root,gltf.animations):{configure(){},spin(){},bounds:()=>visibleBounds(root),groundPitch:0};
 rig.configure(current);const box=rig.bounds(),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());root.position.sub(center);const group=new THREE.Group();group.add(root);const scale=12/Math.max(size.x,size.z);group.scale.setScalar(scale);
 const scene=new THREE.Scene();scene.background=new THREE.Color('#273b4a');scene.add(group);scene.add(new THREE.HemisphereLight('#edf4ff','#71818c',2));const sun=new THREE.DirectionalLight('#fff6e9',2.4);sun.position.set(-16,25,-14);scene.add(sun);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(1.5);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;div.append(renderer.domElement);const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();const camera=new THREE.PerspectiveCamera(34,1,.05,100),orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;views.push({div,root,group,rig,renderer,scene,camera,orbit,kind});pose();
 }catch(e){div.textContent='Render failed: '+e.message;div.dataset.error=e.message;}
}
function displayedBounds(group){const box=new THREE.Box3(),point=new THREE.Vector3();group.traverseVisible(m=>{if(!m.isMesh)return;const positions=m.geometry.attributes.position,index=m.geometry.index;for(let i=0;i<(index?.count??positions.count);i++)box.expandByPoint(point.fromBufferAttribute(positions,index?index.getX(i):i).applyMatrix4(m.matrixWorld));});return box;}
function pose(){for(const v of views){v.rig.configure(current);v.group.rotation.z=parked?-(v.rig.groundPitch??0):0;v.group.position.set(0,0,0);v.group.updateMatrixWorld(true);const box=displayedBounds(v.group);v.group.position.sub(box.getCenter(new THREE.Vector3()));setCamera(v);}}
function setCamera(v){v.orbit.enableDamping=false;v.orbit.update();const distance=Math.max(['dauphin','ec130','bo105','ca60'].includes(id)?30:21,(candidateMode&&id==='ca60'?8:7)/(Math.tan(17*Math.PI/180)*Math.min(1,v.camera.aspect)));v.camera.position.copy(cameraView==='side'?new THREE.Vector3(0,2,-distance):(['f4u','eflash','ec130','bo105','m33','s6b','mc72','ca60'].includes(id)?new THREE.Vector3(-15,3,19):['dauphin','ec130','bo105','m33','s6b','mc72','ca60'].includes(id)?new THREE.Vector3(-15,3,-19):new THREE.Vector3(-15,10,-19)).normalize().multiplyScalar(distance));v.orbit.target.set(0,0,0);v.orbit.update();v.orbit.enableDamping=true;}
$('parked').onclick=()=>{parked=true;current=presetState(true);pose();};$('flight').onclick=()=>{parked=false;current=presetState(false);pose();};$('side').onclick=()=>{cameraView='side';views.forEach(setCamera);};$('perspective').onclick=()=>{cameraView='perspective';views.forEach(setCamera);};
if(candidateMode){await model(`/pack/${asset}/model.glb`,id==='ca60'?'Base · existing Ca.60 geometry repair':'Base download',id==='ca60'?'repaired-base':'raw');for(const alt of meta.alternates.slice(page*3,page*3+3))await model(`/pack/${asset}/alternates/${alt}/model.glb`,alt,'alternate');$('status').textContent=`Candidates ${page*3+1}–${Math.min(page*3+3,meta.alternates.length)} of ${meta.alternates.length}; same camera direction and 12 m normalized span/length. ${id==='ca60'?'Base export aligned to −X forward; water display platform excluded and empty alternate identified.':'Source axis conventions retained.'}`;}
else{
 await model('/models/'+asset+'.glb','ChatGPT version','chatgpt');await model('/models/'+asset+'.glb','Lab version','lab');const reference=meta.refs.find(n=>n.startsWith(refPrefix[id]??'01_'))??meta.refs[0];const div=panel('Historical reference',reference??'No reference supplied');const photo=document.createElement('img');photo.className='photo';photo.src=`/pack/${asset}/reference/web/${reference}`;div.replaceWith(photo);const line=meta.references.split('\n').find(l=>l.includes(reference))??'';const qualification={dauphin:'Dauphin-family reference; original author paint retained. ',ec130:'EC130 reference with different paint; exact B4/T2 identification unverified. ',bo105:'Museum Bo105 reference; source CBS MedEvac paint and configuration differ. ',eflash:'Real ultralight trike: structural reference only; fictional E-Flash paint/type not established. ',m33:'Period M.33; monochrome photo does not establish the red shade. ',s6b:'Preserved S1595; aged museum finish differs from the source author paint. ',mc72:'Preserved M.C.72; museum paint/layout reference. ',ca60:'Museum scale model; palette/layout reference, not mechanical-travel evidence. '};$('panels').lastChild.querySelector('.notes').textContent=(id==='spitfire'?'NMUSAF Mk Vc museum aircraft · related variant; wing armament and markings differ. ':id==='seafire'?'Period Seafire reference · naval details. ':id==='f4u'?'Museum F4U-1D · related F4U-1 family. ':id==='f16'?'Museum production F-16A; source set is YF-16. Paint/variant differ. ':qualification[id]??'')+line.split('|').slice(-3).join(' · ').slice(0,240);$('status').textContent='Matched model cameras; reference variant and pose are identified in the notes.';
 const lab=views.find(v=>v.kind==='lab');if(lab){for(const field of lab.rig.fields.filter(f=>f!=='engine')){const label=document.createElement('label');label.textContent=field;const input=document.createElement('input');input.type='range';input.min=/aileron|elevator|rudder|cyclic|wingPitch|wingRoll|wheelSteer/.test(field)?-100:0;input.max=100;input.value=current[field]*100||0;input.setAttribute('aria-label',field);input.oninput=()=>{current[field]=Number(input.value)/100;pose();};label.append(input);$('controls').append(label);}$('report').textContent=lab.rig.report.summary;}
}
let lastFrame=0;function render(time){requestAnimationFrame(render);if(time-lastFrame<100)return;lastFrame=time;for(const v of views){const w=v.div.clientWidth,h=v.div.clientHeight;v.renderer.setSize(w,h,false);if(v.camera.aspect!==w/h){v.camera.aspect=w/h;v.camera.updateProjectionMatrix();setCamera(v);}v.orbit.update();v.renderer.render(v.scene,v.camera);}}render();
