import * as THREE from 'three';
import {find,meshList,hinge,deflect,flattenVisibility,visibleBounds,clamp,RAD,presetState,rotation,parkingPitch} from './rig-tools.js';
export function prepareSeaplane(root,animations){
 const surfaces={left:[],right:[],elevator:[],rudder:[]};root.traverse(o=>{if(!o.name.startsWith('pivot_'))return;if(/aileronG/.test(o.name))surfaces.left.push(o);if(/aileronD/.test(o.name))surfaces.right.push(o);if(/profondeur/.test(o.name))surfaces.elevator.push(o);if(/direction/.test(o.name))surfaces.rudder.push(o);});
 root.traverse(o=>{if(o.isMesh&&/propblur|propdisc/i.test(o.name))o.visible=false;});const baseline=flattenVisibility(root),mixer=new THREE.AnimationMixer(root),clip=animations.find(a=>a.name==='spin');if(clip)mixer.clipAction(clip).play();
 function configure(s){for(const[m,v]of baseline)m.visible=v;for(const o of surfaces.left)rotation(o,new THREE.Vector3(0,0,1),clamp(s.aileron??0,-1,1)*16);for(const o of surfaces.right)rotation(o,new THREE.Vector3(0,0,1),-clamp(s.aileron??0,-1,1)*16);for(const o of surfaces.elevator)rotation(o,new THREE.Vector3(0,0,1),clamp(s.elevator??0,-1,1)*12);for(const o of surfaces.rudder)rotation(o,new THREE.Vector3(0,1,0),-clamp(s.rudder??0,-1,1)*10);}
 function spin(dt,engine){if(engine>0)mixer.update(dt*engine*2);}
 function update(dt,s,active,paused){if(paused)return;configure({...presetState(false),aileron:active?s.roll/.65:0,elevator:active?s.pitch/.58:0,rudder:active?s.roll/.65:0});spin(dt,active?s.throttle:.06);}
 return{configure,update,spin,bounds:()=>visibleBounds(root),fields:['aileron','elevator','rudder','engine'],isSeaplane:true,report:{limitsDegrees:{aileron:16,elevator:12,rudder:10}}};
}
function cylinderBetween(a,b,r,material){const mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,a.distanceTo(b),12),material);mesh.position.copy(a).add(b).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),b.clone().sub(a).normalize());return mesh;}
function landingGear(root,anchor,wheel,radius,width,name){const group=new THREE.Group();group.name=name;group.position.copy(anchor);const axle=wheel.clone().sub(anchor),metal=new THREE.MeshStandardMaterial({color:'#a9b5c0',metalness:.65,roughness:.4});const tire=new THREE.Mesh(new THREE.TorusGeometry(radius*.75,radius*.25,10,24),new THREE.MeshStandardMaterial({color:'#1b2229',roughness:.9}));tire.position.copy(axle);tire.name=name+'_tire';group.add(tire);const hub=new THREE.Mesh(new THREE.CylinderGeometry(radius*.55,radius*.55,width,18),metal);hub.rotation.x=Math.PI/2;hub.position.copy(axle);hub.name=name+'_hub';group.add(hub);const strut=cylinderBetween(new THREE.Vector3(),axle,.055,metal);strut.name=name+'_strut';group.add(strut);const brace=cylinderBetween(new THREE.Vector3(.2,0,0),axle.clone().multiplyScalar(.6),.025,metal);brace.name=name+'_brace';group.add(brace);root.add(group);return group;}
export function prepareF16(root){
 const hide=n=>find(root,n)?.traverse(o=>{if(o.isMesh)o.visible=false;});
 for(const n of ['i104_outer-pay','i118_middle-pay','i224_inner-pay','i291_pay','i70_tip-pay','i45_Chocks','i12_PW_nozzle','i29_GE_nozzle','i68_brakeL','i69_brakeU','i0_RNLAF_Tailroot','i0_Rudder.002','i0_Rudder.003','i0_Rudder.004','i0_Rudder.005','i0_Rudder.006','i0_CanopyForwardInside','i0_CanopyBackInside'])hide(n);
 root.traverse(o=>{if(o.isMesh&&(/^i0_.*(?:Strut|Tire|GearDoor|MainDoor|ArresterHook)/i.test(o.name)||/Fan|Flame|Spinning/i.test(o.name)))o.visible=false;});
 const surfaces={leftAileron:hinge(root,['i0_LeftLowerAileron','i0_LeftUpperAileron']),rightAileron:hinge(root,['i0_RightLowerAileron','i0_RightUpperAileron']),leftElevator:hinge(root,['i0_LeftLowerHorizonTail','i0_LeftUpperHorizonTail']),rightElevator:hinge(root,['i0_RightLowerHorizonTail','i0_RightUpperHorizonTail']),rudder:hinge(root,['i0_Rudder.001','i0_VstabBandLeftAft','i0_VstabBandRightAft'],'y')};
 const flaps=[hinge(root,['i0_LeftLowerFlap','i0_LeftUpperFlap']),hinge(root,['i0_RightLowerFlap','i0_RightUpperFlap'])];
 const brakes=[];for(const side of ['Left','Right'])for(const half of ['Lower','Upper']){const n=find(root,`i0_${side}${half}Speedbrake`);if(n)brakes.push({surface:hinge(root,[n]),sign:half==='Upper'?1:-1});}
 const gear=[landingGear(root,new THREE.Vector3(-2.97,-.805,0),new THREE.Vector3(-3.02,-1.687,0),.23,.12,'procedural_nose_gear'),landingGear(root,new THREE.Vector3(0,-.65,.45),new THREE.Vector3(.56,-1.50,1.22),.30,.25,'procedural_left_main_gear'),landingGear(root,new THREE.Vector3(0,-.65,-.45),new THREE.Vector3(.56,-1.50,-1.22),.30,.25,'procedural_right_main_gear')];
 const canopy=find(root,'pivot_000_CanopyFrame');const canopyRest=canopy.quaternion.clone();for(const n of ['i0_CanopyForwardOutside','i0_CanopyBackOutside'])find(root,n)?.traverse(o=>{if(o.isMesh)o.material=new THREE.MeshPhysicalMaterial({color:'#718882',metalness:.1,roughness:.19,transparent:true,opacity:.45,depthWrite:false,side:THREE.DoubleSide});});
 const nozzle=new THREE.Group();nozzle.name='procedural_jet_nozzle';nozzle.position.set(4.57,0,0);const shell=new THREE.Mesh(new THREE.CylinderGeometry(.43,.35,.68,24,1,true),new THREE.MeshStandardMaterial({color:'#64717b',metalness:.65,roughness:.4,side:THREE.DoubleSide}));shell.rotation.z=-Math.PI/2;shell.position.x=.34;shell.name='procedural_nozzle_shell';nozzle.add(shell);const ring=new THREE.Mesh(new THREE.TorusGeometry(.355,.035,8,24),new THREE.MeshStandardMaterial({color:'#313941',metalness:.7,roughness:.45}));ring.rotation.y=Math.PI/2;ring.position.x=.69;ring.name='procedural_nozzle_ring';nozzle.add(ring);const glowMat=new THREE.MeshBasicMaterial({color:'#231f26'}),glow=new THREE.Mesh(new THREE.CircleGeometry(.32,32),glowMat);glow.rotation.y=Math.PI/2;glow.position.x=.63;glow.name='procedural_engine_glow';nozzle.add(glow);root.add(nozzle);
 const baseline=flattenVisibility(root);let current=presetState(false);
 function configure(s){s={...presetState(false),...s};for(const[m,v]of baseline)m.visible=v;const g=clamp(s.gear,0,1);gear.forEach((group,i)=>{rotation(group,new THREE.Vector3(0,0,1),(i===0?-100:100)*(1-g));for(const m of meshList(group))m.visible=g>.015;});canopy.quaternion.copy(canopyRest).multiply(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,0,1),-clamp(s.canopy,0,1)*28*RAD));for(const a of flaps)deflect(a,-clamp(s.flaps,0,1)*20);for(const b of brakes)deflect(b.surface,b.sign*clamp(s.speedbrake,0,1)*35);deflect(surfaces.leftAileron,clamp(s.aileron,-1,1)*15);deflect(surfaces.rightAileron,-clamp(s.aileron,-1,1)*15);deflect(surfaces.leftElevator,clamp(s.elevator,-1,1)*12);deflect(surfaces.rightElevator,clamp(s.elevator,-1,1)*12);deflect(surfaces.rudder,-clamp(s.rudder,-1,1)*15);glowMat.color.set(s.engine>.3?'#dc863c':'#231f26');}
 function update(dt,s,active,paused){if(paused)return;const target={aileron:active?s.roll/.65:0,elevator:active?s.pitch/.58:0,rudder:active?s.roll/.65:0};for(const key of Object.keys(target))current[key]+=(clamp(target[key],-1,1)-current[key])*(1-Math.exp(-dt*9));configure({...current,engine:active?s.throttle:0});}
 configure(presetState(true));const groundPitch=parkingPitch(root,['procedural_nose_gear_tire'],['procedural_left_main_gear_tire','procedural_right_main_gear_tire']);configure(current);return{configure,update,spin(){},surfaces,bounds:()=>visibleBounds(root),fields:['gear','canopy','flaps','aileron','elevator','rudder','speedbrake','engine'],groundPitch,report:{limitsDegrees:{aileron:15,elevator:12,rudder:15,flaps:20,speedbrake:35,canopy:28}}};
}
