import * as THREE from 'three';
import {meshList,categorize,presetState,inspectAppearance} from './rig-tools.js';
const $=id=>document.getElementById(id);
const signedFields=['aileron','elevator','rudder','cyclicPitch','cyclicRoll','wingPitch','wingRoll','wheelSteer'];
const labels={hook:'Arrester hook',gear:'Landing gear',fold:'Wing fold',canopy:'Canopy opening',flaps:'Flaps',aileron:'Ailerons',elevator:'Elevators / stabilators',rudder:'Rudder',speedbrake:'Air brakes',cowl:'Cowl flaps',engine:'Engine speed',doors:'Cabin doors',collective:'Collective pitch',cyclicPitch:'Cyclic pitch',cyclicRoll:'Cyclic roll',wingPitch:'Wing pitch',wingRoll:'Wing bank',wheelSteer:'Nose-wheel steering',compression:'Gear compression',wheelRoll:'Wheel rotation phase',rollTrim:'Aileron trim',pitchTrim:'Elevator trim',yawTrim:'Rudder trim',cooling:'Coolant outlet',oil:'Oil outlet',propPitch:'Propeller pitch',stores:'External stores',lights:'Navigation lights',slats:'Leading-edge slats',groundIntakes:'Ground intakes'};
export function createInspector({renderer,camera,orbit,aircraft,worldScene,planes,models,rigs,selectPlane,onClose,onFly}){
 const scene=new THREE.Scene();scene.background=new THREE.Color('#243747');scene.fog=new THREE.Fog('#243747',80,220);scene.environment=worldScene.environment;scene.add(new THREE.HemisphereLight('#edf4ff','#71818c',2));const key=new THREE.DirectionalLight('#fff6e9',2.4);key.position.set(-16,25,-14);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.camera.left=key.shadow.camera.bottom=-24;key.shadow.camera.right=key.shadow.camera.top=24;key.shadow.camera.near=.1;key.shadow.camera.far=70;key.shadow.normalBias=.02;scene.add(key);const fill=new THREE.DirectionalLight('#b4d9ff',1);fill.position.set(15,9,10);scene.add(fill);
 const floor=new THREE.Mesh(new THREE.PlaneGeometry(220,220),new THREE.MeshStandardMaterial({color:'#637484',roughness:.94,metalness:0}));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;scene.add(floor);const grid=new THREE.GridHelper(100,40,'#95acbc','#7f96a8');grid.position.y=.006;grid.material.transparent=true;grid.material.opacity=.2;scene.add(grid);
 let index=0,active=false,state=presetState(true),parked=true,appearance='textured',page=0,parts=[],overrides=new Map();
 const select=$('devAircraft');planes.forEach((p,i)=>{const o=document.createElement('option');o.value=i;o.textContent=p.name;select.append(o);});
 function positionAircraft(){aircraft.position.set(0,0,0);aircraft.rotation.set(parked?(rigs[index]?.groundPitch??0):0,0,0);aircraft.updateMatrixWorld(true);let low=Infinity;models[index]?.traverseVisible(o=>{if(o.isMesh&&!/prop|blade|hub|pdisk/i.test(o.name)){const positions=o.geometry.attributes.position,point=new THREE.Vector3();for(let j=0;j<positions.count;j++)low=Math.min(low,point.fromBufferAttribute(positions,j).applyMatrix4(o.matrixWorld).y);}});const labRig=rigs[index];if(parked&&state.gear===1&&labRig?.report?.lab&&labRig.groundContacts?.length){low=Math.min(...labRig.groundContacts.map(c=>new THREE.Vector3().fromArray(c.glb).applyMatrix4(labRig.groundRoot.matrixWorld).y));}else if(parked&&state.gear===1&&labRig?.nativeScale&&labRig.groundContacts?.length){low=Math.min(...labRig.groundContacts.map(c=>c.clone().applyMatrix4(labRig.root.matrixWorld).y));}aircraft.position.y=(Number.isFinite(low)?-low:0)+(parked?(rigs[index]?.nativeScale&&state.gear===1?0:.025)-(rigs[index]?.waterDraft??0)*(models[index]?.scale.x??1):3.5);aircraft.updateMatrixWorld(true);}
 function apply(reposition=false){const rig=rigs[index];if(!rig)return;rig.configure(state);for(const[m,v]of overrides)m.visible=v;if(reposition)positionAircraft();$('devPose').textContent=parked?(rig.isSeaplane?'MOORED ON WATER':'PARKED ON APRON'):'FLIGHT CONFIGURATION';}
 function format(key,value){if(rigs[index]?.formatValue)return rigs[index].formatValue(key,value);const signedRange=rigs[index]?.report?.signedRanges?.[key];if(signedRange)return Math.round(signedRange[0]+(signedRange[1]-signedRange[0])*(value+1)/2)+'°';const range=rigs[index]?.report?.normalizedRanges?.[key];if(range)return Math.round(range[0]+(range[1]-range[0])*value)+'°';if(['hook','aileron','elevator','rudder','fold','flaps','speedbrake','cowl','doors','collective','cyclicPitch','cyclicRoll','wingPitch','wingRoll','wheelSteer'].includes(key)){const lim=rigs[index]?.report?.limitsDegrees?.[key]??0;if(Array.isArray(lim))return Math.round(value*(value<0?-lim[0]:lim[1]))+'°';return Math.round(value*lim)+'°';}return Math.round(value*100)+'%';}
 function buildControls(){
  const rig=rigs[index],liveries=rig?.liveries,native=Array.isArray(liveries);$('liverySelect').disabled=false;
  $('labLivery').hidden=native?!liveries.length:!liveries;$('liverySelect').replaceChildren();
  if(liveries){const options=native?liveries.map((l,i)=>({value:String(i),label:l.name})):[{value:'',label:liveries.defaultLabel},...liveries.options];
   for(const option of options){const o=document.createElement('option');o.value=option.value;o.textContent=option.label;$('liverySelect').append(o);}
   $('liverySelect').value=native?String(rig.getLivery()):liveries.selected??'';
   $('liverySelect').onchange=async e=>{const value=e.target.value;e.target.disabled=true;try{await (native?rig.setLivery(Number(value)):liveries.select(value));if(native&&rig===rigs[index]){appearance='textured';$('surfaceStyle').value=appearance;inspectAppearance(models[index],appearance);}}finally{if(rig===rigs[index])$('liverySelect').disabled=false;}};
  }
  const box=$('rigControls');box.replaceChildren();for(const key of rig?.fields??[]){state[key]??=0;const label=rig.labels?.[key]??labels[key]??key,row=document.createElement('label');row.className='rig-slider';
   row.innerHTML=`<span>${label}<output>${format(key,state[key])}</output></span><input type="range" min="${(rig.signedFields??signedFields).includes(key)?-100:0}" max="100" step="1" value="${state[key]*100}" aria-label="${label}">`;
   row.querySelector('input').oninput=e=>{state[key]=Number(e.target.value)/100;apply(key!=='engine');row.querySelector('output').textContent=format(key,state[key]);if(rig.nativeScale)for(const [i,field]of rig.fields.entries())box.children[i].querySelector('output').textContent=format(field,state[field]);syncVisibility();};box.append(row);
  }
 }
 function collectParts(){parts=meshList(models[index]);const groups=[...new Set(parts.map(p=>categorize(p)))].sort();$('partGroup').innerHTML='<option value="">All groups</option>';for(const g of groups){const o=document.createElement('option');o.value=g;o.textContent=g;$('partGroup').append(o);}const list=$('visibilityGroups');list.replaceChildren();for(const g of groups){const l=document.createElement('label');l.className='visibility-row';const input=document.createElement('input');input.type='checkbox';input.dataset.group=g;input.onchange=()=>{for(const p of parts.filter(p=>categorize(p)===g))overrides.set(p,input.checked);apply(false);syncVisibility();};l.append(input,document.createTextNode(g));list.append(l);}page=0;syncVisibility();}
 function syncVisibility(){for(const cb of $('visibilityGroups').querySelectorAll('input')){const matches=parts.filter(p=>categorize(p)===cb.dataset.group),count=matches.filter(p=>p.visible).length;cb.checked=count===matches.length;cb.indeterminate=count>0&&count<matches.length;}renderParts();$('partCount').textContent=parts.filter(p=>p.visible).length+' / '+parts.length+' visible';}
 function filtered(){const q=$('partSearch').value.trim().toLowerCase(),g=$('partGroup').value;return parts.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(!g||categorize(p)===g));}
 function renderParts(){const all=filtered(),max=Math.max(0,Math.ceil(all.length/35)-1);page=Math.min(page,max);const list=$('partList');list.replaceChildren();for(const p of all.slice(page*35,(page+1)*35)){const l=document.createElement('label');l.className='part-row';const cb=document.createElement('input');cb.type='checkbox';cb.checked=p.visible;cb.onchange=()=>{overrides.set(p,cb.checked);apply(false);syncVisibility();};const text=document.createElement('span');text.textContent=p.name;l.title=p.userData.labHiddenReason??p.userData.hiddenReason??p.userData.repairReason??categorize(p);l.append(cb,text);list.append(l);}$('partPage').textContent=all.length?(page+1)+' / '+(max+1):'No matching parts';$('partsPrev').disabled=page===0;$('partsNext').disabled=page===max;}
 function setPreset(isParked){if(!models[index])return;parked=isParked;state=rigs[index]?.preset?.(isParked)??presetState(isParked);overrides.clear();appearance='textured';$('surfaceStyle').value=appearance;inspectAppearance(models[index],appearance);apply(true);buildControls();syncVisibility();$('parkedPreset').classList.toggle('selected',parked);$('flightPreset').classList.toggle('selected',!parked);}
 function switchAircraft(i){index=i;selectPlane(i);select.value=String(i);overrides=new Map();$('devAircraftNote').textContent=rigs[i]?.report?.summary??'';$('devAircraftNote').classList.toggle('hidden',!rigs[i]?.report?.summary);$('devFlyBtn').disabled=!models[i];if(!models[i]){parts=[];$('rigControls').innerHTML='<p class="hint">Loading this aircraft…</p>';$('visibilityGroups').replaceChildren();syncVisibility();return;}parts=meshList(models[i]);setPreset(true);collectParts();floor.material.color.set(rigs[i].isSeaplane?'#345f73':'#637484');floor.material.roughness=rigs[i].isSeaplane?.3:.94;grid.visible=!rigs[i].isSeaplane;setCamera('perspective');}
 function setCamera(view){camera.up.set(0,1,0);orbit.target.set(0,4,0);const center=orbit.target.clone();if(view==='front')camera.position.copy(center).add(new THREE.Vector3(0,3,-25));else if(view==='side')camera.position.copy(center).add(new THREE.Vector3(27,2,0));else if(view==='top')camera.position.copy(center).add(new THREE.Vector3(0,30,.01));else camera.position.copy(center).add(new THREE.Vector3(18,10,-22));orbit.update();}
 function open(i){active=true;camera.near=.05;camera.far=250;camera.updateProjectionMatrix();scene.add(aircraft);$('devPanel').classList.remove('hidden');$('devCaption').classList.remove('hidden');orbit.enabled=true;orbit.enablePan=true;orbit.autoRotate=false;orbit.minDistance=4;orbit.maxDistance=80;orbit.minPolarAngle=.01;orbit.maxPolarAngle=Math.PI*.49;renderer.shadowMap.enabled=true;switchAircraft(i);}
 function close(){active=false;camera.near=.3;camera.far=60000;camera.updateProjectionMatrix();for(let i=0;i<models.length;i++){if(models[i])inspectAppearance(models[i],'textured');rigs[i]?.configure(rigs[i]?.preset?.(false)??presetState(false));}worldScene.add(aircraft);$('devPanel').classList.add('hidden');$('devCaption').classList.add('hidden');orbit.enablePan=false;renderer.shadowMap.enabled=false;camera.up.set(0,1,0);}
 select.onchange=()=>switchAircraft(Number(select.value));$('closeDev').onclick=onClose;$('devFlyBtn').onclick=onFly;$('parkedPreset').onclick=()=>setPreset(true);$('flightPreset').onclick=()=>setPreset(false);$('resetRigBtn').onclick=()=>setPreset(parked);$('surfaceStyle').onchange=e=>{appearance=e.target.value;if(models[index])inspectAppearance(models[index],appearance);};$('restoreVisibility').onclick=()=>{overrides.clear();apply(false);syncVisibility();};$('partSearch').oninput=$('partGroup').onchange=()=>{page=0;renderParts();};$('partsPrev').onclick=()=>{page--;renderParts();};$('partsNext').onclick=()=>{page++;renderParts();};for(const b of document.querySelectorAll('[data-dev-camera]'))b.onclick=()=>setCamera(b.dataset.devCamera);
 function tick(dt){if(!active)return;apply(false);rigs[index]?.spin(dt,state.engine);if(rigs[index]?.nativeScale)for(const [mesh,visible]of overrides)mesh.visible=visible;orbit.update();camera.setViewOffset(innerWidth,innerHeight,innerWidth>750?-Math.min(innerWidth*.15,230):0,innerWidth<=750?innerHeight*.1:0,innerWidth,innerHeight);}
 return{scene,open,close,tick,loaded(i){if(active&&i===index)switchAircraft(i);},getState:()=>({aircraft:planes[index].id,parked,...state}),configure(s){state={...state,...s};apply(true);buildControls();syncVisibility();return this.getState();}};
}
