import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createFlight,stepFlight,clamp } from './flight.js';
import { prepareCaproni } from './caproni.js';
import { prepareAdditionalAircraft } from './additional-aircraft.js';
import { prepareCorsair } from './corsair.js';
import { prepareF16,prepareSeaplane } from './aircraft-rigs.js';
import { repairMaterials,presetState } from './rig-tools.js';
import { createInspector } from './inspector.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id);
const planes=[
 {id:'s6b',name:'Supermarine S.6B',detail:'Twin floats · Sleek monoplane',file:'man-supermarine-s-6b-366f4f6d.glb',pace:1},
 {id:'mc72',name:'Macchi Castoldi M.C.72',detail:'Twin floats · Twin propellers',file:'man-macchi-castoldi-mc72-6fa2f786.glb',pace:1.12},
 {id:'m33',name:'Macchi M.33',detail:'Flying boat · High wing',file:'fg-macchi-m33-70f57d9d.glb',pace:.85},
 {id:'f4u',name:'Vought F4U Corsair',detail:'Gull-wing fighter · Three-blade propeller',file:'fg-f4u-8cea7feb.glb',pace:1.2},
 {id:'f16',name:'General Dynamics F-16',detail:'Jet fighter · Single engine',file:'fg-f16-defa67fc.glb',pace:1.5},
 {id:'ca60',name:'Caproni Ca.60 Transaereo',detail:'Nine wings · Eight engines · Flying boat',file:'man-caproni-ca60-e193e5f3.glb',pace:.72},
 {id:'eflash',name:'E-Flash',detail:'Ultralight trike · Weight-shift wing',file:'fg-e-flash-c73b47ce.glb',pace:.6,agility:.65},
 {id:'bo105',name:'BO 105',detail:'Helicopter · Four-blade main rotor',file:'fg-bo105-5f1245bd.glb',pace:.65,agility:.6},
 {id:'dauphin',name:'Dauphin',detail:'Helicopter · Enclosed tail rotor',file:'fg-dauphin-ea380a4c.glb',pace:.7,agility:.6},
 {id:'ec130',name:'EC130',detail:'Helicopter · Three-blade main rotor',file:'fg-ec130-9797aa83.glb',pace:.6,agility:.6},
 {id:'spitfire',name:'Supermarine Spitfire Mk Vb',detail:'Fighter · Three-blade propeller',file:'fg-spitfire-spitfirevb-371986bf.glb',pace:1.15},
 {id:'seafire',name:'Supermarine Seafire Mk III',detail:'Naval fighter · Folding wings',file:'fg-spitfire-seafireiiic-e1e7c198.glb',pace:1.1}
];
let renderer,scene,camera,orbit,aircraft,water,waterShader,selected=5,mode='hangar',paused=false,flight=createFlight(),cameraMode='chase',loaded=0,clock=new THREE.Clock(),lastHud=0,timer,needsResume=false,inspector,firstInspection=true;
const keys=new Set(),models=[],islands=[],mixers=[],aircraftRigs=[];
const touch=matchMedia('(pointer:coarse)').matches;
const up=new THREE.Vector3(0,1,0),forward=new THREE.Vector3(),desiredCamera=new THREE.Vector3(),desiredTarget=new THREE.Vector3(),smoothTarget=new THREE.Vector3();
function notify(text){$('notice').textContent=text;$('notice').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('notice').classList.remove('visible'),3200);}
function fail(message){$('errorPanel').classList.remove('hidden');$('errorText').textContent=message;}
for(let i=0;i<planes.length;i++){
 const p=planes[i],b=document.createElement('button');b.className='aircraft'+(i===selected?' selected':'');b.setAttribute('aria-pressed',i===selected?'true':'false');b.innerHTML=`<span class="plane-number">${String(i+1).padStart(2,'0')}</span><span><strong>${p.name}</strong><small>${p.detail}</small></span><span class="check">${i===selected?'✓':''}</span>`;b.addEventListener('click',()=>selectPlane(i));$('aircraftList').append(b);
}
function selectPlane(i){if(!Number.isInteger(i)||!planes[i])throw new Error('Choose '+planes.map(p=>p.id).join(', ')+'.');selected=i;models.forEach((m,j)=>{if(m)m.visible=i===j});[...$('aircraftList').children].forEach((b,j)=>{b.classList.toggle('selected',i===j);b.setAttribute('aria-pressed',String(i===j));b.querySelector('.check').textContent=i===j?'✓':''});$('previewName').textContent=planes[i].name;$('flightName').textContent=planes[i].name;updateLoading();if(renderer&&!models[i]&&!planes[i].loading&&!planes[i].failed)loadPlane(i);}
function updateLoading(){const ready=!!models[selected];$('flyBtn').disabled=!ready;$('flyBtn').textContent=ready?'Take flight':planes[selected].failed?'Retry aircraft':'Loading aircraft…';if(planes[selected].failed){$('flyBtn').disabled=false;}}
function heightAt(x,z,island){const dx=(x-island.x)/island.rx,dz=(z-island.z)/island.rz,r=Math.sqrt(dx*dx+dz*dz);if(r>=1)return -5;const base=Math.pow(1-r*r,1.7)*island.height;const rugged=(Math.sin(x*.014+z*.008)*Math.sin(z*.017-x*.004)+Math.sin(x*.042+z*.022)*.25)*island.height*.22*Math.min(1,(1-r)*6);return Math.max(-3,base+rugged-4);}
function surfaceAt(x,z){let h=0;for(const island of islands){if(Math.abs(x-island.x)<island.rx&&Math.abs(z-island.z)<island.rz)h=Math.max(h,heightAt(x,z,island));}return h;}
function makeWorld(){
 scene=new THREE.Scene();scene.background=new THREE.Color('#a1d4e5');scene.fog=new THREE.FogExp2('#a5cfda',.00016);
 scene.add(new THREE.HemisphereLight('#d2eeff','#4e6b74',2.5));const sun=new THREE.DirectionalLight('#fff0ce',3.3);sun.position.set(-900,1700,-900);scene.add(sun);
 const sky=new THREE.Mesh(new THREE.SphereGeometry(45000,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:{top:{value:new THREE.Color('#428eca')},bottom:{value:new THREE.Color('#c9e5e8')},sunDirection:{value:sun.position.clone().normalize()}},vertexShader:'varying vec3 vP;void main(){vP=position;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:'varying vec3 vP;uniform vec3 top;uniform vec3 bottom;uniform vec3 sunDirection;void main(){vec3 d=normalize(vP);float t=pow(max(d.y,0.),.48);vec3 c=mix(bottom,top,t);float s=max(dot(d,sunDirection),0.);c+=vec3(1.,.83,.56)*pow(s,1200.)*.9+vec3(.25,.19,.08)*pow(s,12.);gl_FragColor=vec4(c,1.);}'}));sky.frustumCulled=false;scene.add(sky);
 const waterMaterial=new THREE.MeshStandardMaterial({color:'#278f9f',metalness:.42,roughness:.3});waterMaterial.onBeforeCompile=s=>{s.uniforms.uTime={value:0};waterShader=s;s.vertexShader='uniform float uTime;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\n transformed.z += sin(position.x*.013 + uTime*.65)*.9 + cos(position.y*.018+uTime*.8)*.65;');s.vertexShader=s.vertexShader.replace('#include <beginnormal_vertex>','#include <beginnormal_vertex>\n objectNormal=normalize(vec3(-cos(position.x*.013+uTime*.65)*.14,sin(position.y*.018+uTime*.8)*.12,1.));');};water=new THREE.Mesh(new THREE.PlaneGeometry(18000,18000,180,180),waterMaterial);water.rotation.x=-Math.PI/2;scene.add(water);
 const specs=[[-620,-350,420,700,180],[720,-1400,700,580,230],[-1200,-2300,630,470,280],[350,-3000,550,830,195],[1750,-3200,550,650,230],[-2000,-4700,850,600,330],[800,-5300,900,600,300],[2400,350,750,600,290],[-1600,1300,800,630,255],[850,2400,660,580,225],[-3400,-1500,1000,600,355],[3300,-5500,950,800,300]];
 const treeGeo=new THREE.ConeGeometry(5,17,5),treeMat=new THREE.MeshStandardMaterial({color:'#235d4b',roughness:1});const trees=new THREE.InstancedMesh(treeGeo,treeMat,720);const dummy=new THREE.Object3D();let treeCount=0;
 const sand=new THREE.Color('#c5ba8a'),green=new THREE.Color('#55916c'),rock=new THREE.Color('#748885');
 let seed=919;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 for(const [x,z,rx,rz,height]of specs){const island={x,z,rx,rz,height};islands.push(island);const geo=new THREE.PlaneGeometry(rx*2,rz*2,68,68);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;const colors=[];for(let i=0;i<pos.count;i++){const h=heightAt(pos.getX(i)+x,pos.getZ(i)+z,island);pos.setY(i,h);const c=h<7?sand.clone():h>height*.64?rock.clone():green.clone();c.multiplyScalar(.88+.12*Math.sin(pos.getX(i)*.09+pos.getZ(i)*.07));colors.push(c.r,c.g,c.b);}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const terrain=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));terrain.position.set(x,0,z);scene.add(terrain);for(let i=0;i<70&&treeCount<720;i++){const tx=x+(rand()*2-1)*rx*.85,tz=z+(rand()*2-1)*rz*.85,ty=heightAt(tx,tz,island);if(ty>14&&ty<height*.7){dummy.position.set(tx,ty+8,tz);dummy.scale.setScalar(.65+rand()*1.15);dummy.rotation.y=rand()*Math.PI*2;dummy.updateMatrix();trees.setMatrixAt(treeCount++,dummy.matrix);}}}trees.count=treeCount;trees.instanceMatrix.needsUpdate=true;scene.add(trees);
 const cloudGeo=new THREE.SphereGeometry(1,10,7),cloudMat=new THREE.MeshStandardMaterial({color:'#f3f8fa',roughness:1,flatShading:false});const clouds=new THREE.InstancedMesh(cloudGeo,cloudMat,180);for(let i=0;i<180;i++){const cluster=Math.floor(i/5);const cx=Math.sin(cluster*13.27)*5200,cz=Math.cos(cluster*9.48)*5200;dummy.position.set(cx+(i%5-2)*43,650+(cluster%4)*95+Math.sin(i*1.3)*18,cz+Math.sin(i)*35);dummy.scale.set(48+rand()*38,18+rand()*17,35+rand()*38);dummy.rotation.set(0,0,0);dummy.updateMatrix();clouds.setMatrixAt(i,dummy.matrix);}scene.add(clouds);
 aircraft=new THREE.Group();scene.add(aircraft);aircraft.position.set(0,105,350);
}
async function loadPlane(i){const p=planes[i];if(p.loading)return;p.loading=true;p.failed=false;updateLoading();try{const gltf=await new GLTFLoader().loadAsync('/models/'+p.file);const content=gltf.scene;repairMaterials(content,Math.min(8,renderer.capabilities.getMaxAnisotropy()));const rig=['eflash','bo105','dauphin','ec130','spitfire','seafire'].includes(p.id)?prepareAdditionalAircraft(content,p.id):p.id==='ca60'?prepareCaproni(content):p.id==='f4u'?prepareCorsair(content):p.id==='f16'?prepareF16(content):prepareSeaplane(content,gltf.animations);aircraftRigs[i]=rig;const box=rig.bounds(),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3());const wrapper=new THREE.Group();content.position.sub(center);wrapper.add(content);wrapper.rotation.y=-Math.PI/2;wrapper.scale.setScalar(12/Math.max(size.x,size.z));wrapper.visible=i===selected;aircraft.add(wrapper);models[i]=wrapper;p.loading=false;loaded++;updateLoading();inspector?.loaded(i);if(firstInspection&&i===selected){firstInspection=false;openDev();}}catch(e){p.loading=false;p.failed=true;console.error('Aircraft load failed',p.id,e);if(selected===i)notify('This aircraft did not load. Try again or select another plane.');updateLoading();}}
function openDev(){if(!models[selected]){notify('The aircraft is still loading.');return;}mode='dev';paused=false;keys.clear();$('pauseDialog').close();$('hangar').classList.add('hidden');$('sceneCaption').classList.add('hidden');$('flightHud').classList.add('hidden');$('crosshair').classList.add('hidden');$('touchControls').classList.add('hidden');$('modeLabel').textContent='AIRCRAFT INSPECTOR';inspector.open(selected);}
function closeDev(){showHangar();}
function startFlight(){if(mode==='dev')inspector.close();aircraftRigs[selected]?.configure(presetState(false));if(!models[selected]){loadPlane(selected);return;}mode='flight';paused=false;cameraMode='chase';document.activeElement?.blur();resetFlight(false);$('hangar').classList.add('hidden');$('sceneCaption').classList.add('hidden');$('flightHud').classList.remove('hidden');$('crosshair').classList.remove('hidden');$('touchControls').classList.toggle('hidden',!touch);$('cameraBtn').textContent='Chase view';$('modeLabel').textContent='FREE FLIGHT';orbit.enabled=false;notify(touch?'Use the arrow pad to fly. Hold BOOST to speed up.':'You’re flying. W to climb, A / D to turn.');}
function resetFlight(announce=true){flight=createFlight();aircraft.position.set(flight.x,flight.y,flight.z);aircraft.rotation.set(0,0,0);camera.position.set(0,flight.y+9,flight.z+30);smoothTarget.set(0,flight.y+2,flight.z-25);orbit.target.copy(aircraft.position);if(announce)notify('Back above the water.');}
function showHangar(){if(mode==='dev')inspector?.close();mode='hangar';$('modeLabel').textContent='FREE FLIGHT';paused=false;keys.clear();$('pauseDialog').close();$('hangar').classList.remove('hidden');$('sceneCaption').classList.remove('hidden');$('flightHud').classList.add('hidden');$('crosshair').classList.add('hidden');$('touchControls').classList.add('hidden');aircraft.position.set(0,105,350);aircraft.rotation.set(0,0,0);orbit.enabled=true;orbit.autoRotate=!matchMedia('(prefers-reduced-motion:reduce)').matches;orbit.minDistance=15;orbit.maxDistance=65;orbit.target.copy(aircraft.position);setHangarCamera();}
function setHangarCamera(){camera.position.set(22,115,326);orbit.target.copy(aircraft.position);orbit.update();}
function toggleCamera(){if(mode!=='flight')return;cameraMode=cameraMode==='chase'?'orbit':'chase';orbit.enabled=cameraMode==='orbit';orbit.autoRotate=false;orbit.minDistance=16;orbit.maxDistance=90;orbit.target.copy(aircraft.position);$('cameraBtn').textContent=cameraMode==='chase'?'Chase view':'Orbit view';$('crosshair').classList.toggle('hidden',cameraMode!=='chase');notify(cameraMode==='orbit'?'Orbit view: drag to look around.':'Chase view');}
function setPaused(value){if(mode!=='flight')return;paused=value;keys.clear();$('modeLabel').textContent=value?'PAUSED':'FREE FLIGHT';if(value){if(!$('pauseDialog').open)$('pauseDialog').showModal();}else{$('pauseDialog').close();clock.getDelta();}}
function resize(){if(!renderer)return;const w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.setViewOffset(w,h,mode==='hangar'&&w>650?-Math.min(w*.15,220):0,mode==='hangar'&&w<=650?h*.13:0,w,h);camera.updateProjectionMatrix();}
function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),t=clock.elapsedTime;if(waterShader)waterShader.uniforms.uTime.value=t;mixers.forEach(m=>m?.update(paused||$('helpDialog').open?0:dt*(mode==='flight'?2:.12)));aircraftRigs.forEach((rig,i)=>{if(i===selected&&mode!=='dev')rig?.update(dt,flight,mode==='flight',paused||$('helpDialog').open);});
 if(mode==='flight'&&!paused&&!$('helpDialog').open){const prev=aircraft.position.clone();const input={pitch:Number(keys.has('w')||keys.has('ArrowUp'))-Number(keys.has('s')||keys.has('ArrowDown')),turn:Number(keys.has('a')||keys.has('ArrowLeft'))-Number(keys.has('d')||keys.has('ArrowRight')),throttle:Number(keys.has('e'))-Number(keys.has('q')),boost:keys.has('Shift')};stepFlight(flight,input,dt,planes[selected].pace,planes[selected].agility??1);if(flight.y<surfaceAt(flight.x,flight.z)+4){resetFlight(false);notify('A close call! Your plane is back in the air.');}aircraft.position.set(flight.x,flight.y,flight.z);aircraft.rotation.set(flight.pitch,flight.yaw,flight.roll,'YXZ');if(cameraMode==='chase'){forward.set(-Math.sin(flight.yaw),0,-Math.cos(flight.yaw));desiredCamera.copy(aircraft.position).addScaledVector(forward,-29);desiredCamera.y+=9;desiredTarget.copy(aircraft.position).addScaledVector(forward,30);desiredTarget.y+=flight.pitch*18+1;camera.position.lerp(desiredCamera,1-Math.exp(-dt*5));smoothTarget.lerp(desiredTarget,1-Math.exp(-dt*5));camera.up.lerp(up,dt*4);camera.lookAt(smoothTarget);}else{const delta=aircraft.position.clone().sub(prev);camera.position.add(delta);orbit.target.copy(aircraft.position);orbit.update();}if(t-lastHud>.1){$('speedValue').textContent=Math.round(flight.speed*3.6);$('altValue').textContent=Math.round(flight.y);$('headingValue').textContent=String(Math.round(((-flight.yaw*180/Math.PI)%360+360)%360)).padStart(3,'0');$('throttleValue').textContent=Math.round(flight.throttle*100)+'%';$('throttleBar').style.width=flight.throttle*100+'%';lastHud=t;}
 }else if(mode==='hangar'){aircraft.position.y=105+Math.sin(t*.7)*.18;orbit.update();}
 const w=innerWidth,h=innerHeight,ox=mode==='hangar'&&w>650?-Math.min(w*.15,220):0,oy=mode==='hangar'&&w<=650?h*.13:0;if(camera.view?.offsetX!==ox||camera.view?.offsetY!==oy)camera.setViewOffset(w,h,ox,oy,w,h);if(mode==='dev')inspector.tick(dt);renderer.render(mode==='dev'?inspector.scene:scene,camera);
}
$('devBtn').onclick=$('inspectBtn').onclick=openDev;$('flyBtn').onclick=startFlight;$('hangarBtn').onclick=showHangar;$('pauseHangarBtn').onclick=showHangar;$('resumeBtn').onclick=()=>setPaused(false);$('cameraBtn').onclick=toggleCamera;$('resetBtn').onclick=()=>resetFlight();$('helpBtn').onclick=()=>{needsResume=mode==='flight'&&!paused;keys.clear();$('helpDialog').showModal();};$('closeHelp').onclick=()=>$('helpDialog').close();$('helpDialog').addEventListener('close',()=>{keys.clear();clock.getDelta();});$('pauseDialog').addEventListener('cancel',e=>{e.preventDefault();setPaused(false);});
window.addEventListener('keydown',e=>{if(e.target.closest('input,select,textarea')&&e.key!=='Escape')return;const k=e.key.length===1?e.key.toLowerCase():e.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(k))e.preventDefault();if(e.repeat){keys.add(k);return;}if($('helpDialog').open)return;if(k==='Escape'&&mode==='dev'){closeDev();return;}if(k==='Escape'&&mode==='flight'){e.preventDefault();setPaused(!paused);}else if(k==='c')toggleCamera();else if(k==='r'&&mode==='flight')resetFlight();else if(!paused)keys.add(k);});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));window.addEventListener('blur',()=>{keys.clear();if(mode==='flight'&&!$('helpDialog').open)setPaused(true);});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='flight')setPaused(true);});window.addEventListener('resize',resize);
for(const b of document.querySelectorAll('[data-key]')){b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(b.dataset.key);});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.key));}
try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.95;renderer.shadowMap.type=THREE.PCFSoftShadowMap;camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.3,60000);makeWorld();const pmrem=new THREE.PMREMGenerator(renderer);const room=new RoomEnvironment();scene.environment=pmrem.fromScene(room,.04).texture;room.dispose();pmrem.dispose();orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.dampingFactor=.065;orbit.enablePan=false;orbit.autoRotateSpeed=.35;orbit.maxPolarAngle=Math.PI*.49;orbit.minPolarAngle=.4;inspector=createInspector({renderer,camera,orbit,aircraft,worldScene:scene,planes,models,rigs:aircraftRigs,selectPlane,onClose:closeDev,onFly:startFlight});showHangar();selectPlane(selected);resize();animate();renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();fail('The 3D view was interrupted. Reload to restart your flight.');});}catch(e){console.error(e);fail('This demo needs WebGL. Please enable graphics acceleration in your browser and reload.');}
if(document.modelContext?.registerTool){const common={annotations:{readOnlyHint:false,untrustedContentHint:false}};const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool)).catch(console.warn);}catch(e){console.warn(e);}};register({...common,name:'select_aircraft',title:'Select aircraft',description:'Return to the hangar and select one of the twelve aircraft.',inputSchema:{type:'object',properties:{aircraft:{type:'string',enum:planes.map(p=>p.id)}},required:['aircraft'],additionalProperties:false},execute:({aircraft:id})=>{const i=planes.findIndex(p=>p.id===id);if(i<0)throw new Error('Unknown aircraft');showHangar();selectPlane(i);return {aircraft:id,name:planes[i].name,ready:!!models[i]};}});register({...common,name:'start_flight',title:'Start flight',description:'Start flying the selected plane. The aircraft must be loaded.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{if(!models[selected])throw new Error('Aircraft is still loading');startFlight();return{mode,aircraft:planes[selected].id};}});register({name:'read_flight_state',title:'Read flight state',description:'Read the selected plane and current flight instruments.',annotations:{readOnlyHint:true,untrustedContentHint:false},inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>({mode,paused,aircraft:planes[selected].id,loaded:!!models[selected],speedKmh:Math.round(flight.speed*3.6),altitudeM:Math.round(flight.y),camera:cameraMode,inspection:mode==='dev'?inspector.getState():null})});}
