import * as THREE from 'three';
export const RAD=Math.PI/180;
export const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
export const find=(root,name)=>root.getObjectByName(THREE.PropertyBinding.sanitizeNodeName(name));
export function meshList(node){const a=[];node?.traverse(o=>{if(o.isMesh)a.push(o);});return a;}
export function visibleBounds(root){root.updateMatrixWorld(true);const box=new THREE.Box3();root.traverseVisible(o=>{if(o.isMesh){o.geometry.computeBoundingBox();box.union(o.geometry.boundingBox.clone().applyMatrix4(o.matrixWorld));}});return box;}
// Find the resting pitch from actual tire vertices after the common -90° yaw.
export function parkingPitch(root,frontNodes,rearNodes){
 root.updateMatrixWorld(true);const inv=root.matrixWorld.clone().invert();
 const points=nodes=>nodes.flatMap(node=>meshList(typeof node==='string'?find(root,node):node).flatMap(m=>{const tr=inv.clone().multiply(m.matrixWorld),a=m.geometry.attributes.position,result=[];for(let i=0;i<a.count;i++)result.push(new THREE.Vector3().fromBufferAttribute(a,i).applyMatrix4(tr));return result;}));
 const front=points(frontNodes),rear=points(rearNodes);if(!front.length||!rear.length)return 0;
 const low=(ps,a)=>Math.min(...ps.map(p=>p.y*Math.cos(a)-p.x*Math.sin(a))),gap=a=>low(rear,a)-low(front,a);let a=-20*RAD,b=25*RAD;
 if(gap(a)*gap(b)>0)return 0;for(let i=0;i<40;i++){const mid=(a+b)/2;if(gap(mid)*gap(a)>0)a=mid;else b=mid;}return(a+b)/2;
}
export function flattenVisibility(root){const effective=new Map();root.traverse(o=>{if(o.isMesh){let v=true;for(let p=o;p;p=p.parent){v&&=p.visible;if(p===root)break;}effective.set(o,v);}});root.traverse(o=>{o.visible=o.isMesh?effective.get(o):true;});return effective;}
export function hinge(root,objects,spanAxis='z',parent=root){
 const nodes=objects.map(x=>typeof x==='string'?find(root,x):x).filter(Boolean);if(!nodes.length)throw new Error('Missing moving surface: '+objects.join(','));root.updateMatrixWorld(true);const inv=root.matrixWorld.clone().invert(),points=[],v=new THREE.Vector3();
 for(const node of nodes)for(const mesh of meshList(node)){const tr=inv.clone().multiply(mesh.matrixWorld),a=mesh.geometry.attributes.position;for(let i=0;i<a.count;i++)points.push(v.fromBufferAttribute(a,i).applyMatrix4(tr).clone());}
 const span=p=>p[spanAxis],lo=Math.min(...points.map(span)),hi=Math.max(...points.map(span)),edge=[];
 for(let i=0;i<12;i++){const a=lo+(hi-lo)*i/12,b=lo+(hi-lo)*(i+1)/12,slice=points.filter(p=>span(p)>=a&&span(p)<=b);if(!slice.length)continue;const x=Math.min(...slice.map(p=>p.x)),near=slice.filter(p=>p.x<x+.035);edge.push(near.reduce((s,p)=>s.add(p),new THREE.Vector3()).multiplyScalar(1/near.length));}
 const mean=edge.reduce((s,p)=>s.add(p),new THREE.Vector3()).multiplyScalar(1/edge.length),other=spanAxis==='z'?'y':'z';let variance=0,cx=0,co=0;for(const p of edge){const d=span(p)-span(mean);variance+=d*d;cx+=d*(p.x-mean.x);co+=d*(p[other]-mean[other]);}
 const axis=spanAxis==='z'?new THREE.Vector3(cx/Math.max(variance,1e-8),co/Math.max(variance,1e-8),1):new THREE.Vector3(cx/Math.max(variance,1e-8),1,co/Math.max(variance,1e-8));axis.normalize();const group=new THREE.Group();group.name='repaired_hinge_'+nodes[0].name;group.position.copy(mean);root.add(group);root.updateMatrixWorld(true);for(const n of nodes)group.attach(n);root.updateMatrixWorld(true);if(parent!==root)parent.attach(group);return {hinge:group,mesh:nodes[0],axis,rest:group.quaternion.clone(),angle:0,origin:mean.clone()};
}
export function deflect(surface,degrees){if(!surface)return;surface.angle=degrees*RAD;surface.hinge.quaternion.copy(surface.rest).multiply(new THREE.Quaternion().setFromAxisAngle(surface.axis,surface.angle));}
export function rotation(node,axis,angle){node?.quaternion.setFromAxisAngle(axis,angle*RAD);}
export function groupParts(root,names,origin,name){const group=new THREE.Group();group.name=name;group.position.copy(origin);root.add(group);root.updateMatrixWorld(true);for(const n of names){const o=typeof n==='string'?find(root,n):n;if(o)group.attach(o);}return group;}
export function captureTransforms(root){const a=[];root.traverse(o=>{a.push({o,p:o.position.clone(),q:o.quaternion.clone()});});return()=>{for(const{ o,p,q }of a){o.position.copy(p);o.quaternion.copy(q);}};}
export function clipPoser(root,clip){if(!clip)return()=>{};const bindings=clip.tracks.map(t=>{const dot=t.name.lastIndexOf('.'),node=find(root,t.name.slice(0,dot)),property=t.name.slice(dot+1);return{node,property,interp:t.createInterpolant()};}).filter(x=>x.node);return time=>{for(const b of bindings){const v=b.interp.evaluate(time);if(b.property==='quaternion')b.node.quaternion.fromArray(v).normalize();else if(b.property==='position')b.node.position.fromArray(v);}};}
export function repairMaterials(root,anisotropy=8){const done=new Set();root.traverse(o=>{if(!o.isMesh)return;o.frustumCulled=false;o.castShadow=true;o.receiveShadow=true;const array=Array.isArray(o.material);const mats=(array?o.material:[o.material]).map(m=>{if(!m)return m;const c=m.clone();c.userData={...m.userData};c.side=THREE.FrontSide;c.ior=1.5;c.specularIntensity=.25;c.specularColor?.set('#ffffff');c.envMapIntensity=.35;c.metalness=Math.min(c.metalness??0,.3);c.roughness=Math.max(c.roughness??.6,.48);if(c.map){c.map.colorSpace=THREE.SRGBColorSpace;c.map.anisotropy=anisotropy;const name=c.map.name.toLowerCase();if(/logo|number/.test(name)){c.alphaTest=.12;c.transparent=false;c.depthWrite=true;c.polygonOffset=true;c.polygonOffsetFactor=-1;c.polygonOffsetUnits=-1;}if(/pdisk|propdisc|propblur/.test(name)){c.transparent=true;c.alphaTest=.02;c.depthWrite=false;}done.add(c.map);}if(c.transparent)c.side=THREE.DoubleSide;return c;});o.material=array?mats:mats[0];});return done.size;}
export function inspectAppearance(root,kind){root.traverse(o=>{if(!o.isMesh)return;const list=Array.isArray(o.material)?o.material:[o.material];for(const m of list){m.userData.baseMap??=m.map||null;m.userData.baseColor??=m.color.clone();m.userData.baseVertexColors??=m.vertexColors;m.wireframe=kind==='wireframe';if(kind==='clay'||kind==='wireframe'){m.map=null;m.vertexColors=false;m.color.set(kind==='clay'?'#9dabb7':'#6196b8');}else{m.map=m.userData.baseMap;m.vertexColors=m.userData.baseVertexColors;m.color.copy(m.userData.baseColor);}m.needsUpdate=true;}});}
export const presetState=parked=>({gear:parked?1:0,fold:parked?1:0,canopy:0,flaps:0,aileron:0,elevator:0,rudder:0,speedbrake:0,cowl:0,engine:0});
export function categorize(part){if(typeof part!=='string'&&part.userData.inspectorGroup)return part.userData.inspectorGroup;const s=(typeof part==='string'?part:part.name).toLowerCase();if(s.startsWith('original_rotor_'))return'Original rotor / propeller';if(s.startsWith('original_crew_'))return'Crew';if(s.startsWith('original_equipment_'))return'Optional equipment';if(s.startsWith('original_variant_'))return'Original export variants';if(/procedural.*rotor.*blur/.test(s))return'Blur discs';if(/procedural.*rotor/.test(s))return'New rotors';if(/sail|weight_shift|wingkeel/.test(s))return'Wings';if(/doorfl|doorfr|doorbl|doorbr|door_front|door_back|portecrew|porte[ab][dg]/.test(s))return'Cabin doors';if(/propdisk|propdisc|pdisk|propblur|propeller_blur/.test(s))return'Blur discs';if(/procedural.*propeller|procedural_blade/.test(s))return'New propeller';if(/(^i0_prop$)|hubturn/.test(s))return'Original propeller';if(/rocket|aim|agm|gbu|mk-?8|cbu|b61|500lb|1000lb|tank|pylon|lau|mxu|an_|sniper|hts|legion/.test(s))return'External stores';if(/chock|extinguisher|equipment|cabin_node|equipment_node/.test(s))return'Ground equipment';if(/canopy|glass|vitre/.test(s))return'Canopy / glass';if(/gear|wheel|tire|strut|doorlogo/.test(s))return'Landing gear';if(/aileron|elevator|rudder|profondeur|direction|flap|speedbrake/.test(s))return'Control surfaces';if(/light|strobe|beacon/.test(s))return'Lights';if(/nozzle|fan|turbine|flame|engine|moteur/.test(s))return'Engine';return'Airframe';}
