import assert from 'node:assert/strict';import * as THREE from 'three';import {fixture} from './fixture.mjs';import {prepareEc130Lab} from '../../src/lab/ec130.js';import {labFind} from '../../src/lab/lab-tools.js';import {meshList} from '../../src/rig-tools.js';
const {root,facts,animations}=await fixture('fg-ec130-9797aa83'),rig=await prepareEc130Lab(root,animations,facts);const near=(a,b,e=1e-6)=>assert(Math.abs(a-b)<e,`${a} vs ${b}`),center=n=>{root.updateMatrixWorld(true);return new THREE.Box3().setFromObject(labFind(root,n)).getCenter(new THREE.Vector3());};
assert(rig.report.originalAnimationDisabled);near(rig.groundPitch*180/Math.PI,-.96);assert.deepEqual(rig.groundContacts,[]);assert(!rig.fields.includes('gear'),'Fixed skids have no invented retraction');
for(const [rotor,index]of [[rig.mainRotor,0],[rig.tailRotor,1]]){const spec=facts.fdm_geometry.rotors[index];assert.equal(rotor.count,spec.blades);assert(rotor.mount.position.equals(new THREE.Vector3().fromArray(spec.glb)));let radius=0;for(const b of rotor.blades)for(const m of meshList(b)){const p=m.geometry.attributes.position;for(let i=0;i<p.count;i++)radius=Math.max(radius,Math.hypot(p.getX(i),p.getZ(i)));}assert(Math.abs(radius/(spec.diameter_m/2)-1)<.03);const a=rotor.rotor.rotation.y;rotor.spin(.01,1);near(rotor.rotor.rotation.y-a,-.01*spec.rpm*Math.PI/30);}
rig.configure({doors:0});const door=center('doorbl'),fuselage=center('fuselage');rig.configure({doors:1});const moved=center('doorbl');near(moved.x-door.x,.85);near(moved.z-door.z,.07);assert(center('fuselage').equals(fuselage),'Cabin doors move independently of fuselage');
const angle=i=>rig.bindings.filter(b=>b.anim.sourceIndex===i).map(b=>b.anim.type==='translate'?b.angle:b.angle*180/Math.PI);for(const [i,v]of [[25,-80],[28,70],[31,-18],[32,90],[33,-100],[42,-90],[43,-77],[45,70]]){assert(angle(i).length);angle(i).forEach(a=>near(a,v));}
for(const v of [-100,100]){rig.configure(Object.fromEntries(rig.fields.map(k=>[k,v])));for(const b of rig.bindings){const value=b.anim.type==='translate'?b.angle:b.angle*180/Math.PI;assert(value>=Math.min(...b.anim.travel)-1e-6&&value<=Math.max(...b.anim.travel)+1e-6);}}
rig.configure({collective:0,cyclicPitch:0,cyclicRoll:0,rudder:-1});near(rig.mainRotor.blades[0].rotation.z*180/Math.PI,.5);near(rig.tailRotor.blades[0].rotation.z*180/Math.PI,-16.8);rig.configure({collective:1,rudder:1});near(rig.mainRotor.blades[0].rotation.z*180/Math.PI,16);near(rig.tailRotor.blades[0].rotation.z*180/Math.PI,34.2);const shaft=rig.mainRotor.mount.quaternion.clone();rig.configure({cyclicPitch:1,cyclicRoll:1});assert(rig.mainRotor.mount.quaternion.equals(shaft));
rig.configure({doors:0});assert(labFind(root,'fuselage').visible);assert(!labFind(root,'fuselage_t2').visible);assert(meshList(labFind(root,'doorbr_t2')).every(m=>!m.visible));assert(meshList(labFind(root,'floats_deflated')).every(m=>!m.visible));assert(meshList(root).filter(m=>!m.visible).every(m=>m.userData.labHiddenReason));assert(rig.report.textures.applied.length>=70);assert(labFind(root,'fuselage').material.userData.labTexture.endsWith('FLIGHTGEAR.png'));assert.equal(rig.liveries.options.length,0);
// Overall length is measured over the complete rotor sweep, not one three-blade azimuth.
root.updateMatrixWorld(true);const body=new THREE.Box3().setFromObject(labFind(root,'fuselage')),sweptLength=body.max.x-(rig.mainRotor.mount.position.x-rig.mainRotor.radius);assert(Math.abs(sweptLength/12.64-1)<.05);assert(Math.abs(rig.mainRotor.diameter/10.69-1)<.03);
const h=rig.bounds().getSize(new THREE.Vector3()).y;assert(h>3.34*1.05,'Source model height exceeds unqualified published value; limitation recorded rather than distorting geometry');assert(rig.report.sourceLimitNotes.hub&&rig.report.sourceLimitNotes.ground);const spin=rig.mainRotor.rotor.rotation.y;rig.update(.2,{throttle:1,pitch:1,roll:1},true,true);near(spin,rig.mainRotor.rotor.rotation.y);
console.log('EC130 Lab: B4 variant, exact asymmetric XML doors/compound slide, rotor radius/count/hubs/RPM/incidence, fixed skids, recovered source paint, hidden reasons and pause passed. Height/hub source conflicts recorded.');
