import assert from 'node:assert/strict';
import * as THREE from 'three';
import {interp,xmlPivot,channel,hideByCondition,evalExpression,contactsPitch,placeOnGround,applyTextures,liverySwitch,fdmRotor,fdmPropeller,sourceGlass} from '../../src/lab/lab-tools.js';

assert.equal(interp([[0,0],[.1,0],[.2,90],[1,90]],-.5),0);
assert(Math.abs(interp([[0,0],[.1,0],[.2,90],[1,90]],.15)-45)<1e-10);
assert.equal(interp([[0,0],[.1,0],[.2,90],[1,90]],2),90);
const root=new THREE.Group(),parent=new THREE.Group();parent.position.set(2,0,0);root.add(parent);
const mesh=new THREE.Mesh(new THREE.BoxGeometry(1,.1,1),new THREE.MeshStandardMaterial());mesh.name='i0_Wing';mesh.position.set(1,0,0);parent.add(mesh);
root.updateMatrixWorld(true);const before=mesh.getWorldPosition(new THREE.Vector3());
const surface=xmlPivot(root,{type:'rotate',objects:['Wing'],glb_nodes:['i0_Wing'],glb_center:[2,0,0],glb_axis_dir:[0,0,1]});
assert(mesh.getWorldPosition(new THREE.Vector3()).distanceTo(before)<1e-10);surface.apply(90);
assert(mesh.getWorldPosition(new THREE.Vector3()).distanceTo(new THREE.Vector3(2,1,0))<1e-10);
surface.apply(0);assert(mesh.getWorldPosition(new THREE.Vector3()).distanceTo(before)<1e-10);
const c=channel({animations_from_xml:[]},'elevator');assert.equal(c.evaluate({factor:30,travel:[-30,20]},100),20);assert.equal(c.evaluate({factor:30,travel:[-30,20]},-100),-30);
const property=text=>({op:'property',text}),value=text=>({op:'value',text}),condition={op:'condition',children:[{op:'and',children:[{op:'not',children:[property('rain')]},{op:'equals',children:[property('engine'),value('2')]}]}]};
assert.equal(evalExpression(condition,{rain:false,engine:2}),true);assert.equal(evalExpression(condition,{rain:true,engine:2}),false);assert.equal(evalExpression(condition,{rain:false}),null);
const facts={source_conditions:[{type:'select',source_xml:'verified.xml',objects:['Wing'],condition}],fdm_geometry:{parked_pitch_deg_nose_up:12.04,gear_contacts_trusted:true,gear_contacts:[{glb:[0,-2,0],is_wheel:true}]}};
hideByCondition(root,facts,{rain:true,engine:2});assert(!mesh.visible);assert(mesh.userData.labHiddenReason.includes('verified.xml'));
hideByCondition(root,facts,{rain:false,engine:2});assert(mesh.visible);assert.equal(contactsPitch(facts),12.04*Math.PI/180);assert(placeOnGround(root,facts).trusted);
const conflicting={source_conditions:[{type:'select',source_xml:'false.xml',objects:['Wing'],condition:value('false')},{type:'select',source_xml:'true.xml',objects:['Wing'],condition:value('true')}]};
hideByCondition(root,conflicting,{});assert(!mesh.visible,'Every applicable XML select must pass');hideByCondition(root,{...conflicting,source_conditions:conflicting.source_conditions.toReversed()},{});assert(!mesh.visible,'Select order cannot reveal a rejected part');
const map=new THREE.Texture();map.flipY=false;map.colorSpace=THREE.SRGBColorSpace;
const textureFacts={texture_by_part:[{has_uv:true,texture:'original.png',glb_nodes:['i0_Wing']}],textures:[{original:'original.png',file:'textures/paint.png',cutout_alpha:true}],livery_names:[{name:'Real author livery',slots:{paint:'textures/other.png'}}]};
const applied=await applyTextures(root,textureFacts,'/lab/test',{loader:async()=>map});assert.equal(applied.applied.length,1);assert.equal(mesh.material.map,map);assert.equal(mesh.material.alphaTest,.12);
const other=new THREE.Texture(),livery=liverySwitch(root,textureFacts,'/lab/test',{loader:async()=>other,slots:{paint:['i0_Wing']}});assert.equal(livery.options[0].label,'Real author livery');await livery.select('Real author livery');assert.equal(mesh.material.map,other);assert.equal(mesh.material.userData.baseMap,other);await livery.select('');assert.equal(mesh.material.map,map);
let finishLate;const racing=liverySwitch(root,textureFacts,'/lab/test',{loader:()=>new Promise(resolve=>{finishLate=resolve;}),slots:{paint:['i0_Wing']}});
const delayed=racing.select('Real author livery');await racing.select('');finishLate(other);await delayed;assert.equal(mesh.material.map,map,'Reset cancels paint downloads from an older selection');
const rotorRoot=new THREE.Group(),rotor=fdmRotor(rotorRoot,{fdm_geometry:{rotors:[{diameter_m:10.69,blades:3,rpm:394,glb:[1,2,3],glb_normal:[0,1,0],ccw:true}]}},{name:'test'});
assert.equal(rotor.diameter,10.69);assert.equal(rotor.blades.length,3);assert(rotor.mount.position.equals(new THREE.Vector3(1,2,3)));rotor.setPitch(10,2,-3);assert(rotor.mount.position.equals(new THREE.Vector3(1,2,3)));const angle=rotor.rotor.rotation.y;rotor.spin(.2,0);assert.equal(rotor.rotor.rotation.y,angle);rotor.spin(.2,1);assert.notEqual(rotor.rotor.rotation.y,angle);
const prop=fdmPropeller(new THREE.Group(),{fdm_geometry:{propellers:[{radius_m:1.638}]},real_world_specs:{'prop blade number':'3'},propellers_rotors:[{type:'spin',property:'engines/rpm',glb_center:[0,0,0]}]},{name:'test'});assert.equal(prop.radius,1.638);assert.equal(prop.count,3);
sourceGlass(root,['i0_Wing'],'Test source effect');assert(mesh.material.isMeshPhysicalMaterial);assert('PHYSICAL' in mesh.material.defines,'Standard copy must preserve physical shader define');assert.equal(mesh.material.transmission,1);
console.log('Lab shared helpers: XML pivots, interpolation, asymmetric clamps, Boolean conditions, contacts, textures/liveries, FDM rotors and propellers passed.');
